version: "3.9"
services:
  app:
    container_name: nrl-webhook-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8030:8030"
    volumes:
      - ./share:/usr/app/share
